export const bondListSelectors = {
  newLink: 'a[href="/portal_service/bonds/new"]',
  generateTermsButton: 'button[data-target="#generate_term"]',
  tomboFilterContainer: '.select2-selection__rendered[title="Tombo"]',
  select2OpenSearch: '.select2-container--open .select2-search__field',
  select2Options: '.select2-results__option',
  searchForm: '#bond_search',
  title: 'h1',
  table: 'table',
  rows: 'tbody tr',
  rowCheckbox: 'input[type="checkbox"]',
  editAction: 'a[href*="/edit"]',
  successMessage: '.bootstrap-growl.alert.alert-success',
}

export const bondFormSelectors = {
  cardTitle: '.card-header h6',
  area: '#set_area',
  subarea: '#resp_subarea',
  responsibleCollaborator: '#bond_employee_type_colaborador',
  responsibleNone: '#bond_employee_type_sem_usuario',
  collaborator: '#collaborators',
  collaboratorContainer: '#select2-collaborators-container',
  select2Options: '.select2-results__option',
  select2OpenSearch: '.select2-container--open .select2-search__field',
  option: 'option',
  attendedBy: '#attended',
  modalityInPerson: '#bond_modality_presencial',
  modalityHomeOffice: '#bond_modality_home_office',
  officeCheckbox: '#check_office',
  officeSelect: '#key',
  observation: '#bond_observation',
  addAssetButton: '#btn_asset',
  assetSelect: '#set_tombo',
  assetDescription: '#set_description',
  assetStatus: '#set_status',
  requiredMark: 'code',
  body: 'body',
  saveInput: 'input[type="submit"][value="Salvar"]',
  saveButton: 'button',
  cancelButton: 'a, button',
}

export const bondEditSelectors = {
  area: '#set_area',
  subarea: '#resp_subarea',
  option: 'option',
  selectedOption: 'option:selected',
  responsibleCollaborator: '#bond_employee_type_colaborador',
  responsibleNone: '#bond_employee_type_sem_usuario',
  attendedBy: '#attended',
  modalityInPerson: '#bond_modality_presencial',
  modalityHomeOffice: '#bond_modality_home_office',
  operatingSystem: '#so',
  officeCheckbox: '#check_office',
  officeSelect: '#key',
  observation: '#bond_observation',
  addAssetButton: '#btn_asset',
  assetSelect: '#set_tombo',
  assetDescription: '#set_description',
  newAssetStatus: '#set_status',
  assetRows: '.nested-fields.add_ativo',
  removeAssetButton: 'a.remove_fields',
  assetStatusSelect: 'select[name*="[status_id]"]',
  defectDescriptionInput: 'input[name*="[observation]"]',
  body: 'body',
  saveInput: 'input[type="submit"][value="Salvar"]',
  saveButton: 'button',
  cancelButton: 'a, button',
}
